package api

import (
	"os"

	"github.com/gin-gonic/gin"
	apiv1 "github.com/shekhar8352/PostEaze/api/v1"
	"github.com/shekhar8352/PostEaze/constants"
	"github.com/shekhar8352/PostEaze/middleware"

	docs "github.com/shekhar8352/PostEaze/docs" // swagger docs (generated by swag)
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           PostEaze API
// @version         1.0
// @description     Auto-generated API documentation with Swagger
// @host            localhost:8000
// @BasePath        /
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func Init() error {
	// create a server
	// s := server.Default(
	// 	server.WithHostPorts(fmt.Sprintf(":%d", flags.Port())),
	// 	server.WithKeepAlive(true),
	// )

	host := os.Getenv("API_HOST")

	docs.SwaggerInfo.Title = "PostEaze API"
	docs.SwaggerInfo.Description = "Auto-generated API documentation with Swagger"
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = host
	docs.SwaggerInfo.BasePath = "/api/v1"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	s := gin.Default()
	s.Use(middleware.GinLoggingMiddleware())

	api := s.Group(constants.ApiRoute)

	api.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status": "ok",
		})
	})
	
	v1 := api.Group(constants.V1Route)
	{
		addV1UserAuthRoutes(v1)
		addV1LogRoutes(v1)
	}

	// Swagger endpoint
	s.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// this is a blocking call unless application receives shut down signal
	// or some error occurs
	return s.Run()
}

func addV1UserAuthRoutes(v1 *gin.RouterGroup) {
	authv1 := v1.Group(constants.AuthRoute)

	authv1.POST(constants.SignUpRoute, apiv1.SignupHandler)
	authv1.POST(constants.LogInRoute, apiv1.LoginHandler)
	authv1.POST(constants.RefreshRoute, middleware.AuthMiddleware(), apiv1.RefreshTokenHandler)
	authv1.POST(constants.LogOutRoute, middleware.AuthMiddleware(), apiv1.LogoutHandler)
}

func addV1LogRoutes(v1 *gin.RouterGroup) {
	logv1 := v1.Group(constants.LogRoute)
	logv1.GET(constants.LogByDate, apiv1.GetLogsByDate)
	logv1.GET(constants.LogById, apiv1.GetLogByIDHandler)
}
