package api

import (
	"os"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	apiv1 "github.com/shekhar8352/PostEaze/api/v1"
	"github.com/shekhar8352/PostEaze/api/webhooks"
	"github.com/shekhar8352/PostEaze/constants"
	"github.com/shekhar8352/PostEaze/middleware"

	docs "github.com/shekhar8352/PostEaze/docs" // swagger docs (generated by swag)
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           PostEaze API
// @version         1.0
// @description     Auto-generated API documentation with Swagger
// @host            localhost:8000
// @BasePath        /
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func Init() error {
	// create a server
	// s := server.Default(
	// 	server.WithHostPorts(fmt.Sprintf(":%d", flags.Port())),
	// 	server.WithKeepAlive(true),
	// )

	host := os.Getenv("API_HOST")

	docs.SwaggerInfo.Title = "PostEaze API"
	docs.SwaggerInfo.Description = "Auto-generated API documentation with Swagger"
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = host
	docs.SwaggerInfo.BasePath = "/api/v1"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	s := gin.Default()

	s.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:5173", "https://dev.posteaze.in"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		AllowCredentials: true,
	}))

	s.Use(middleware.GinLoggingMiddleware())

	api := s.Group(constants.ApiRoute)

	api.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status": "ok",
		})
	})

	v1 := api.Group(constants.V1Route)
	{
		addV1UserAuthRoutes(v1)
		addV1LogRoutes(v1)
		addV1UserRoutes(v1)
		addV1TeamRoutes(v1)
		addV1MetaRoutes(v1)
		addV1ChannelRoutes(v1)
		addV1DevRoutes(v1)
		addV1CronRoutes(v1)
		addV1AnalyticsRoutes(v1)
		addV1PostRoutes(v1)
	}

	// Swagger endpoint
	api.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// this is a blocking call unless application receives shut down signal
	// or some error occurs
	return s.Run()
}

func addV1UserAuthRoutes(v1 *gin.RouterGroup) {
	authv1 := v1.Group(constants.AuthRoute)

	authv1.POST(constants.Authenticate, apiv1.AuthenticateWithFirebaseHandler)
	authv1.POST(constants.RefreshRoute, middleware.AuthMiddleware(), apiv1.RefreshTokenHandler)
	authv1.POST(constants.LogOutRoute, middleware.AuthMiddleware(), apiv1.LogoutHandler)
	authv1.GET("/me", middleware.AuthMiddleware(), apiv1.GetLoggedInUserHandler)
}

func addV1LogRoutes(v1 *gin.RouterGroup) {
	logv1 := v1.Group(constants.LogRoute)
	logv1.GET(constants.LogByDate, apiv1.GetLogsByDate)
	logv1.GET(constants.LogById, apiv1.GetLogByIDHandler)
}

func addV1UserRoutes(v1 *gin.RouterGroup) {
	userv1 := v1.Group(constants.UserRoute)
	userv1.GET(constants.GetUserById, apiv1.GetUserByIdHandler)
	userv1.PUT(constants.UpdateUser, apiv1.UpdateUserHandler)
}

func addV1TeamRoutes(v1 *gin.RouterGroup) {
	teamv1 := v1.Group(constants.TeamRoute)
	teamv1.POST(constants.CreateTeam, apiv1.CreateTeamHandler)
	teamv1.GET(constants.GetAllTeams, apiv1.GetAllTeamsHandler)
	teamv1.GET(constants.GetTeamById, apiv1.GetTeamByIDHandler)
	teamv1.GET(constants.GetTeamByOwnerID, apiv1.GetTeamByOwnerIDHandler)
	teamv1.PUT(constants.UpdateTeam, apiv1.UpdateTeamHandler)
	teamv1.PUT(constants.UpdateTeamStatus, apiv1.UpdateTeamStatusHandler)
}

func addV1MetaRoutes(v1 *gin.RouterGroup) {
	metav1 := v1.Group(constants.MetaRoute)
	metav1.POST(constants.MetaCallback, apiv1.HandleMetaCallback)
}

func addV1ChannelRoutes(v1 *gin.RouterGroup) {
	channelv1 := v1.Group(constants.ChannelRoute)
	channelv1.GET("", middleware.AuthMiddleware(), apiv1.GetChannelsHandler)
	channelv1.GET("/details", middleware.AuthMiddleware(), apiv1.GetPageDetailsHandler)

	instagramv1 := channelv1.Group(constants.InstagramRoute)
	instagramv1.POST(constants.CreateInstagramChannel, middleware.AuthMiddleware(), apiv1.CreateInstagramChannelHandler)
	instagramv1.POST("/subscribe-webhooks", middleware.AuthMiddleware(), apiv1.SubscribeWebhooksHandler)

	webhookv1 := v1.Group(constants.WebhookRoute)
	webhookv1.GET(constants.InstagramWebhook, webhooks.HandleInstagramWebhookVerify)
	webhookv1.POST(constants.InstagramWebhook, webhooks.HandleInstagramWebhookEvent)
}

func addV1DevRoutes(v1 *gin.RouterGroup) {
	devv1 := v1.Group("/dev")
	devv1.POST("/generate-token", apiv1.GenerateTestTokenHandler)
}

func addV1CronRoutes(v1 *gin.RouterGroup) {
	cronv1 := v1.Group("/cron")
	cronv1.POST("/trigger-instagram-sync", apiv1.TriggerInstagramSyncHandler)
	cronv1.POST("/trigger-instagram-posts", apiv1.TriggerInstagramPostsSyncHandler)
	cronv1.POST("/trigger-instagram-analytics", apiv1.TriggerInstagramAnalyticsSyncHandler)
}

func addV1PostRoutes(v1 *gin.RouterGroup) {
	v1.GET("/posts", middleware.AuthMiddleware(), apiv1.GetPostsHandler)
}

func addV1AnalyticsRoutes(v1 *gin.RouterGroup) {
	analyticsv1 := v1.Group("/channels/:channelId/analytics")
	{
		analyticsv1.GET("/profile", apiv1.GetProfileAnalyticsHandler)
		analyticsv1.GET("/posts", apiv1.GetPostAnalyticsHandler)
		analyticsv1.GET("/overview", apiv1.GetAnalyticsOverviewHandler)
		analyticsv1.GET("/top-posts", apiv1.GetTopPostsHandler)
		analyticsv1.GET("/posts-overview", apiv1.GetPostsOverviewHandler)

		// New endpoints
		analyticsv1.GET("/posts/:postId", apiv1.GetPostInsightsHandler)
		analyticsv1.GET("/dashboard", apiv1.GetChannelDashboardHandler)
		analyticsv1.GET("/comparison", apiv1.GetPeriodComparisonHandler)
	}
}
