version: "3.8"

services:
  backend:
    build: ./backend
    container_name: posteaze-backend
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - postgres
    networks:
      - posteaze

  frontend:
    build: ./frontend
    container_name: posteaze-frontend
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - posteaze

  postgres:
    image: postgres:15-alpine
    container_name: posteaze-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"  # Exposed for team development access
    networks:
      - posteaze

  caddy:
    image: caddy:alpine
    container_name: posteaze-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - posteaze

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  posteaze:
    driver: bridge