env: "dev"

driverName: "postgres"
url: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}/${POSTGRES_DB}?sslmode=disable"
maxOpenConnections: 20
maxIdleConnections: 10
maxConnectionLifetimeInSeconds: 300
maxConnectionIdleTimeInSeconds: 60