env: "prod"

getCatsFact:
  method: "GET"
  url: "http://localhost:8082/account/details"
  timeoutInMillis: 1000
  retryCount: 3
  backoffPolicy:
    constantBackoff:
      intervalInMillis: 2
      maxJitterIntervalInMillis: 5
