env: "prod"

driverName: "postgres"
url: "postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_URL}/${DATABASE_NAME}?sslmode=disable"
maxOpenConnections: 20
maxIdleConnections: 10
maxConnectionLifetimeInSeconds: 300
maxConnectionIdleTimeInSeconds: 60